### ISSUE TITLE
[RFE] Keep pinnned tabs pinned

### ISSUE THREAD

**Issue by pwnorbitals** [petko10/real-time-tab-sync#1]
Could the "pinned" status of a tab be transmitted when syncing tabs? Thanks.

edit: looking at the code, doing this would also make it easy to keep the "muted" status of a tab, so if possible... :)

**Comment by v-ko** [comment]
If you want to contribute the feature it's more than welcome, I'd update the extension. But otherwise it would be at least another two months until I get to doing it , because of the state exams that I have upcoming.

**Comment by pwnorbitals** [comment]
I will try, but I might end up writing another one based on diffs :D I'll keep you up to date
